actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003
batch_size: 256
critic_learning_rate: 0.0003
device: cuda
env_name: "cartpole"
eta: 1.0
eval_episodes: 10
eval_every: 5
eval_seed: 42
gamma: 0.99
group: "edac-cartpole-swingup"
hidden_dim: 256
log_every: 1000
name: "EDAC"
normalize_reward: false
num_critics: 10
tau: 0.005